language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

script:
  - cargo build
  - cargo test
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
      cargo bench;
    fi

notifications:
  email: false
